# This file was generated by GoReleaser. DO NOT EDIT.
cask "revmux" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "eb0d6d3c0ee3b3b14c198283bf1345f3b431d070b3870512492ea29d64a4d099"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4115a596adb8e8f171f7579786bbe3f6d773d9280f664ae8b2895ddc29558d8c"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc54146430978c5a07abd956af629f98343c6f63ee9d4396720b2a2d96461a73"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa92cbb0c18c5b259d6091b284fc8d867e1beea50f41631d96f50d45db54b507"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "revmux"
  desc "Supervised multi-agent code review with parallel claude and codex subprocesses"
  homepage "https://github.com/umputun/revmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "revmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/revmux"]
    end
  end

  # No zap stanza required
end
