# This file was generated by GoReleaser. DO NOT EDIT.
cask "revmux" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "93dff9b22b904dac0f79bbfc4fea9d240f7aba95a5dabdc16a787ba625cabacc"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f512aa28020772d48b9260e48312409a03cb4cf53b29ec16f01037801e92e0d"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e65b05bed622c51227a14999a4c7ddba74aa959c9822fc98c4ca81fca46c067a"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "61990b305d8a73e34c9f7eb900a84eb3e811ed3c0b36c8ca7be61b8952661dac"
      url "https://github.com/hackmajoris/revmux/releases/download/v#{version}/revmux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "revmux"
  desc "Supervised multi-agent code review with parallel claude and codex subprocesses"
  homepage "https://github.com/umputun/revmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "revmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/revmux"]
    end
  end

  # No zap stanza required
end
