# This file was generated by GoReleaser. DO NOT EDIT.
cask "sharefly" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "b06ca494b059d3513b29ffb69db72ab03f34944633bf7afcaec6724efcbb7f2c"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "debb6658e46838f8c0eb59924b4cdf7dc4663d78f06305ffab9f86bf35a0fa13"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "380e3e1ca20dc37620bdf680f5158101b5c870e3d8c4a626b6776c7068274a25"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8aa6cefa1ad32efb820c90026090121fafbb717ffb4122bba53766eba736fac5"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sharefly"
  desc "Share static HTML from your tailnet via a public URL through a Cloudflare Tunnel"
  homepage "https://github.com/hackmajoris/sharefly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sharefly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sharefly"]
    end
  end

  # No zap stanza required
end
