# This file was generated by GoReleaser. DO NOT EDIT.
cask "sharefly" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "25da68b57de1ad44ac9ae3a79375cab6f6589bb217e1d26b33b5eb94dee160be"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ec270ef020013af9d58adf2f494b4ca064ddc39aa9445913b8af3b47a77530b"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "636cd4fa7cd524b10d8302102a3d1f8782ccbd046649837fee17cd3afe45d327"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a948bae81fd6cfef0c7cf7e0c555dbf480f703f4cadec44e212d4cce8969fbf"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sharefly"
  desc "Share static HTML from your tailnet via a public URL through a Cloudflare Tunnel"
  homepage "https://github.com/hackmajoris/sharefly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sharefly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sharefly"]
    end
  end

  # No zap stanza required
end
