# This file was generated by GoReleaser. DO NOT EDIT.
cask "sharefly" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b78bc71c4948b2df5311769c1288d4b1c5c52121286abfce228db81956b9665f"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58f24a26f0d984253eab11a9ba833e52edb9021ffcde0c57b2030769c6335997"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9f37a6a6ca1efb83907652400684e33b70fbf4275eaf62ccb1816c88575fe787"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76021e201c20817020ec159f8f3f4daaa2a11de79eba9dfff0570d76feb86b5a"
      url "https://github.com/hackmajoris/sharefly/releases/download/v#{version}/sharefly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sharefly"
  desc "Share static HTML from your tailnet via a public URL through a Cloudflare Tunnel"
  homepage "https://github.com/hackmajoris/sharefly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sharefly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sharefly"]
    end
  end

  # No zap stanza required
end
